### ISSUE TITLE
Implement `strverscmp`

### ISSUE THREAD

**Issue by sunfishcode** [sunfishcode/eyra#34]
We should implement the `strverscmp` function, in c-scape/src/mem/ntbs.rs, and remove it from c-scape/src/todo.rs.

[Here is the documentation for `strverscmp`](https://man7.org/linux/man-pages/man3/strverscmp.3.html).

I've labeled this a "good first issue", though that's admittedly relative. It requires familiarity with C strings and raw pointers. For some examples, see the other functions in ntbs.rs.

**Comment by KGrewal1** [comment]
I've opened a PR in the c-scape repo https://github.com/sunfishcode/c-ward/pull/99

**Comment by sunfishcode** [comment]
https://github.com/sunfishcode/c-ward/pull/99 is now merged!
